// Third party drivers "should" start from 0x8000
#define MY_DRIVER_DEVICE 0x8000

#define IOCTL_TEST CTL_CODE(MY_DRIVER_DEVICE, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_SKINPROT CTL_CODE(MY_DRIVER_DEVICE, 0x803, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_LOADPROT CTL_CODE(MY_DRIVER_DEVICE, 0x806, METHOD_NEITHER, FILE_ANY_ACCESS)